### ISSUE TITLE
Verifying contract error of compilation has exceeded the maximum timeout on etherscan. (Kovan only)

### ISSUE THREAD

**Issue by drdonjuan** [poanetwork/token-wizard#802] opened 2018-04-20 15:56 UTC
Hello,
Trying to verify a contract on Kovan network. While verifying the contract of "CrowdsaleTokenExt" on etherscan, it displayed the error 
"Error! Unable to verify source code
Exception #1 Occured: ERROR|The Contract solidity compilation has exceeded the maximum timeout/memory limit that we can safely process. Automated source code verification is unavailable for this source code."

Any idea on it please?

**Comment by vbaranov** [comment] 2018-04-23 12:07
Duplicate of #679, #716

**Comment by vbaranov** [comment] 2018-05-24 22:18
The problem is solved: you don't need to put a colon before library name.

**Closed by vbaranov** 2018-05-24 22:18 UTC
Labels: duplicate, question
