### ISSUE TITLE
(Wizard2.0-Dutch)  Rate does not reach given maxRate

### ISSUE THREAD

**Issue by dennis00010011b** [poanetwork/token-wizard#858] opened 2018-05-08 04:37 UTC
Wizard URL: https://5af093921f12b70ce2f90775--architect-coin-64174.netlify.com/
Steps:
1. Create Dutch crowdsale with parameters: 
 decimals=18, supply=1000, 
1 tier: minRate=100, maxRate=1100, duration=10 min, supply=1000
2. Open crowdsale page and check the price value immediately before crowdsale will finish.
Expected result:
 - price should be 1100 (equals of maxRate)
Actual result: 
 - price is 417

Exec ID : 0xce6e1ff85d4382cf3560f6cfaf0922ed56791fc1f7ab1dcd6da580686e1b3308

If you are reporting a problem with Token Wizard, please include the following information:

### Which network did you use? (Mainnet, Kovan, Rinkeby, etc.)

*Ropsten*

### If you were able to create it, what is the URL of your crowdsale?

*https://5af093921f12b70ce2f90775--architect-coin-64174.netlify.com/invest?exec-id=0xce6e1ff85d4382cf3560f6cfaf0922ed56791fc1f7ab1dcd6da580686e1b3308&networkID=3*

### Do you have screenshots showing the problem?

<img width="1440" alt="screen shot 2018-05-07 at 21 06 58" src="https://user-images.githubusercontent.com/14067096/39738202-af2c8812-523e-11e8-965e-235040833523.png">

### Do you see errors in the dev console? If yes, please include a screenshot

To open the dev console in Google Chrome, press F12, or go to `View -> Developer -> Developer Tools`, and open the Console tab

If you see errors, please right click on them and "Save as..". Zip saved file and attach it to the Issue.

*No*

---

**Comment by vbaranov** [comment] 2018-05-14 18:18
@dennis00010011b this is not reproducible for me anymore with the new versions of auth_os registry and applications. Could you check this issue with the latest code from 2.0 branch?

**Comment by dennis00010011b** [comment] 2018-05-15 06:06
Still reproducible with last version of 2.0 , latest commit  https://github.com/poanetwork/token-wizard/commit/18d0cba310cca4092111fe148e552abe533c4d08
Also , function (price-time) non-linear
<img width="1440" alt="screen shot 2018-05-14 at 22 56 57" src="https://user-images.githubusercontent.com/14067096/40039335-dbd9012e-57ca-11e8-8d85-be89ce444580.png">

**Comment by dennis00010011b** [comment] 2018-05-15 06:09
Also, in first seconds after start  value of remaining start was more than total duration

<img width="1440" alt="screen shot 2018-05-14 at 22 47 16" src="https://user-images.githubusercontent.com/14067096/40039588-caf598b2-57cb-11e8-9fa8-4e4de51826b4.png">

**Comment by vbaranov** [comment] 2018-06-12 12:39
>Also, in first seconds after start value of remaining start was more than total duration

@dennis00010011b first seconds is not so critical, and also I think we can't fix it because it depends on `now` variable of Solidity:
https://github.com/auth-os/applications/blob/e754fdfff3dd55087b7655d3d965a0d35990880e/TokenWizard/crowdsale/DutchCrowdsale/contracts/init/InitCrowdsale.sol#L361-L367

There is no another option to calculate remaining time except using `now`

**Comment by vbaranov** [comment] 2018-06-18 15:20
@dennis00010011b could you check all other bugs, you mentioned in this issue after merging https://github.com/poanetwork/token-wizard/pull/960?

**Comment by vbaranov** [comment] 2018-06-26 18:20
The issue exists because the function, which calculates rate, depends on `block.time` which is not continuous. We can't control the behaviour of the `block.time`. Moreover, this issue will be mitigated on real durations of crowdsales. I guess, we should close it.

**Closed by vbaranov** 2018-06-26 18:20 UTC
Labels: auth_os issue, migration to auth-os
