### ISSUE TITLE
(UI Bug) Deployment progress modal looks chaotic when there are six or more tiers

### ISSUE THREAD

**Issue by dennis00010011b** [poanetwork/token-wizard#590] opened 2018-02-10 22:42 UTC
If you are reporting a problem with Token Wizard, please include the following information:

### Which network did you use? (Mainnet, Kovan, Rinkeby, etc.)

*Rinkeby*

### If you were able to create it, what is the URL of your crowdsale?

*https://wizard.poa.network/invest?addr=0x1409a40C3bf91FD6909b902eBC37f9C657610bb4&networkID=4*

### Do you have screenshots showing the problem?
6 tiers
![progresst6](https://user-images.githubusercontent.com/14067096/36067371-704b9ad2-0e70-11e8-8095-61ef2c4bbd5f.png)

10 tiers
![10tiers](https://user-images.githubusercontent.com/14067096/36067372-7f8058e4-0e70-11e8-976f-765ac05d2ef6.png)

### Do you see errors in the dev console? If yes, please include a screenshot

To open the dev console in Google Chrome, press F12, or go to `View -> Developer -> Developer Tools`, and open the Console tab

If you see errors, please right click on them and "Save as..". Zip saved file and attach it to the Issue.

*No*

---

**Comment by vbaranov** [comment] 2018-02-12 10:15
Duplicate of https://github.com/poanetwork/token-wizard/issues/518

**Closed by vbaranov** 2018-02-12 10:15 UTC
Labels: duplicate
