### ISSUE TITLE
When Try To Modify CROWDSALE End date Show Error Message?

### ISSUE THREAD

**Issue by BITSCoin** [poanetwork/token-wizard#752] opened 2018-03-28 04:55 UTC
If you are reporting a problem with Token Wizard, please include the following information:

### Which network did you use? (Mainnet, Kovan, Rinkeby, etc.)

*Mainnet*

### If you were able to create it, what is the URL of your crowdsale?

*https://wizard.oracles.org/manage/0x9E96c74a4e074cb95F4299A661317E8a30244e55*

### Do you have screenshots showing the problem?

*![rorro](https://user-images.githubusercontent.com/37858795/38009356-b6f77f5e-3275-11e8-8db2-287917a06a7b.PNG)
*

### Do you see errors in the dev console? If yes, please include a screenshot

To open the dev console in Google Chrome, press F12, or go to `View -> Developer -> Developer Tools`, and open the Console tab

If you see errors, please right click on them and "Save as..". Zip saved file and attach it to the Issue.

*Your answer*

---

**Comment by dennis00010011b** [comment] 2018-03-28 07:10
Look like it is duplicate of https://github.com/poanetwork/token-wizard/issues/728

**Comment by vbaranov** [comment] 2018-04-06 07:40
Fixed in https://github.com/poanetwork/token-wizard/pull/766

**Closed by vbaranov** 2018-04-06 07:40 UTC
Labels: Manage page, duplicate, logical bug, to do
