### ISSUE TITLE
(Feature) One wallet address for the whole summary

### ISSUE THREAD

**Issue by fernandomg** [poanetwork/token-wizard#817] opened 2018-04-23 18:01 UTC
Refer to: https://github.com/poanetwork/token-wizard/issues/673#issuecomment-373494551

**Comment by mariano-aguero** [comment] 2018-06-29 14:08
To clarify, the feature is related to the branch 2.0

**Comment by vbaranov** [comment] 2018-06-29 14:18
@mariano-aguero as I am aware, this feature is related to master branch, because wallet address is already a property of the whole crowdsale in 2.0 branch.

**Comment by mariano-aguero** [comment] 2018-06-29 14:22
@vbaranov 
I can not reproduce this problem in the branch 2.0, then it happens in the branch master? I think we should put a label or to reference the origin of the branch in the issue, what do you think?  Thanks for the reply

**Comment by vbaranov** [comment] 2018-06-29 14:46
@mariano-aguero 
Just to clarify;
`master` branch is for current TW (Token Wizard) 1.0
`2.0` branch is for upcoming TW 2.0

All issues, that have label `migration to auth-os` are for `2.0` branch.
All issues, that have no label `migration to auth-os` are related to `master` branch

In the future `2.0` branch will be merged to master branch and there will no be `2.0` branch anymore. 

Is such labeling `migration to auth-os` clear and accepted for you? Or do you still think we should create additional labels? Please, let me know

**Comment by fernandomg** [comment] 2018-06-29 14:55
@vbaranov @mariano-aguero In that case, I wasn't using `migration to auth-os` label consistently. Let me review the bugs I created recently to update them and avoid confusions.

**Comment by mariano-aguero** [comment] 2018-06-29 15:01
@vbaranov Its ok for me. Thanks for the clarification

**Closed** 2018-07-02 14:59 UTC
Labels: Step4-Publish, awaiting for review, enhancement
